


enableGlobalCache: true

enableScripts: true

enableTelemetry: false

injectEnvironmentFiles:
  - .env.yarn?

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0086
    level: discard

nmMode: hardlinks-global

nodeLinker: node-modules

npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.13.0.cjs
