import type { ConfigObject } from '../config-schema';
import {
  cancerPreventionEditPrivilege,
  familyPlanningEditPrivilege,
  labourDeliveryEditPrivilege,
  postnatalCareEditPrivilege,
  prenatalCareEditPrivilege,
} from '../constants';

export const maternalFormKeys = [
  'maternalHistory',
  'currentPregnancy',
  'atencionPrenatal',
  'prenatalSupplementationForm',
  'screeningIndicatorsForm',
  'psychoprophylaxisForm',
  'birthPlanForm',
  'deliveryOrAbortion',
  'SummaryOfLaborAndPostpartum',
  'obstetricMonitor',
  'immediatePostpartumPeriod',
  'postpartumControl',
  'maternalDischargeForm',
  'maternalEpicrisisForm',
  'maternalReadmissionForm',
  'obstetricsServiceForm',
  'adolescentPregnancyCareForm',
  'obstetricReferralForm',
  'culturalBirthPreferencesForm',
  'perinatalMentalHealthForm',
  'maternalViolenceScreeningForm',
  'familyPlanningCounselingForm',
  'familyPlanningFollowupForm',
  'cervicalCancerScreeningForm',
  'breastCancerScreeningForm',
] as const satisfies ReadonlyArray<keyof ConfigObject['formsList']>;

export type MaternalFormKey = (typeof maternalFormKeys)[number];

export const formLabels: Partial<Record<keyof ConfigObject['formsList'], string>> = {
  maternalHistory: 'Antecedentes obstétricos',
  currentPregnancy: 'Embarazo actual',
  atencionPrenatal: 'Atención prenatal',
  prenatalSupplementationForm: 'Suplementación gestante',
  screeningIndicatorsForm: 'Tamizaje prenatal',
  psychoprophylaxisForm: 'Psicoprofilaxis obstétrica',
  birthPlanForm: 'Plan de parto',
  deliveryOrAbortion: 'Parto o aborto',
  SummaryOfLaborAndPostpartum: 'Resumen de parto y postparto',
  obstetricMonitor: 'Monitorización obstétrica / partograma',
  immediatePostpartumPeriod: 'Puerperio inmediato',
  postpartumControl: 'Control de puerperio',
  maternalDischargeForm: 'Egreso materno',
  maternalEpicrisisForm: 'Epicrisis obstétrica y postparto',
  maternalReadmissionForm: 'Reingreso materno',
  obstetricsServiceForm: 'Servicio de obstetricia',
  adolescentPregnancyCareForm: 'Atención diferenciada de gestante adolescente',
  obstetricReferralForm: 'Referencia/contrarreferencia obstétrica',
  culturalBirthPreferencesForm: 'Pertinencia cultural y preferencia de parto',
  perinatalMentalHealthForm: 'Salud mental perinatal',
  maternalViolenceScreeningForm: 'Tamizaje de violencia gestante',
  familyPlanningCounselingForm: 'Consejería y método anticonceptivo',
  familyPlanningFollowupForm: 'Seguimiento de planificación familiar',
  cervicalCancerScreeningForm: 'Tamizaje cervical',
  breastCancerScreeningForm: 'Tamizaje de mama',
};

export const formEditPrivileges: Record<MaternalFormKey, string> = {
  maternalHistory: prenatalCareEditPrivilege,
  currentPregnancy: prenatalCareEditPrivilege,
  atencionPrenatal: prenatalCareEditPrivilege,
  prenatalSupplementationForm: prenatalCareEditPrivilege,
  screeningIndicatorsForm: prenatalCareEditPrivilege,
  psychoprophylaxisForm: prenatalCareEditPrivilege,
  birthPlanForm: prenatalCareEditPrivilege,
  adolescentPregnancyCareForm: prenatalCareEditPrivilege,
  perinatalMentalHealthForm: prenatalCareEditPrivilege,
  maternalViolenceScreeningForm: prenatalCareEditPrivilege,
  deliveryOrAbortion: labourDeliveryEditPrivilege,
  SummaryOfLaborAndPostpartum: labourDeliveryEditPrivilege,
  obstetricMonitor: labourDeliveryEditPrivilege,
  obstetricsServiceForm: labourDeliveryEditPrivilege,
  obstetricReferralForm: labourDeliveryEditPrivilege,
  culturalBirthPreferencesForm: labourDeliveryEditPrivilege,
  immediatePostpartumPeriod: postnatalCareEditPrivilege,
  postpartumControl: postnatalCareEditPrivilege,
  maternalDischargeForm: postnatalCareEditPrivilege,
  maternalEpicrisisForm: postnatalCareEditPrivilege,
  maternalReadmissionForm: postnatalCareEditPrivilege,
  familyPlanningCounselingForm: familyPlanningEditPrivilege,
  familyPlanningFollowupForm: familyPlanningEditPrivilege,
  cervicalCancerScreeningForm: cancerPreventionEditPrivilege,
  breastCancerScreeningForm: cancerPreventionEditPrivilege,
};
