import { type FetchResponse, openmrsFetch, restBaseUrl } from '@openmrs/esm-framework';

import { type Patient } from './patient-registration.types';
import { type PatientCreationIdentifierCheckpoint } from './patient-creation-checkpoint';
import {
  fetchAndVerifyCreatedPatient,
  isDefinitivePatientCreateRejection,
  PatientCreationConflictError,
  reconcilePatientCreation,
} from './patient-creation-reconciliation';

const mockOpenmrsFetch = vi.mocked(openmrsFetch);

const identifiers: Array<PatientCreationIdentifierCheckpoint> = [
  {
    fieldName: 'openmrsId',
    identifier: '10001V',
    identifierTypeUuid: 'identifier-type-uuid',
    locationUuid: 'location-uuid',
    preferred: true,
    autoGenerated: true,
    sourceUuid: 'source-uuid',
  },
];

const payload: Patient = {
  uuid: 'client-only-uuid',
  identifiers: [
    {
      identifier: '10001V',
      identifierType: 'identifier-type-uuid',
      location: 'location-uuid',
      preferred: true,
    },
  ],
  person: {
    uuid: 'client-only-uuid',
    names: [
      {
        uuid: '',
        preferred: true,
        givenName: 'Ana María',
        middleName: '',
        familyName: 'Pérez',
        familyName2: 'Rojas',
      },
    ],
    gender: 'F',
    birthdate: '1990-02-03',
    birthdateEstimated: false,
    attributes: [],
    addresses: [],
    dead: false,
  },
};

const serverPatient = {
  uuid: 'server-patient-uuid',
  voided: false,
  identifiers: [
    {
      identifier: '10001V',
      preferred: true,
      voided: false,
      identifierType: { uuid: 'identifier-type-uuid' },
      location: { uuid: 'location-uuid' },
    },
  ],
  person: {
    uuid: 'server-patient-uuid',
    voided: false,
    gender: 'F',
    birthdate: '1990-02-03T00:00:00.000-05:00',
    birthdateEstimated: false,
    dead: false,
    deathDate: null,
    causeOfDeath: null,
    causeOfDeathNonCoded: null,
    preferredName: {
      givenName: 'Ana María',
      middleName: '',
      familyName: 'Pérez',
      familyName2: 'Rojas',
    },
    names: [
      {
        preferred: true,
        voided: false,
        givenName: 'Ana María',
        middleName: '',
        familyName: 'Pérez',
        familyName2: 'Rojas',
      },
    ],
    addresses: [],
    attributes: [],
  },
};

describe('patient creation reconciliation', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('finds one exact identifier and demographic match, then verifies its UUID', async () => {
    mockOpenmrsFetch
      .mockResolvedValueOnce({ data: { results: [serverPatient] } } as never)
      .mockResolvedValueOnce({ data: serverPatient, ok: true } as never);

    await expect(reconcilePatientCreation(identifiers, payload)).resolves.toMatchObject({
      data: { uuid: 'server-patient-uuid' },
    });
    expect(mockOpenmrsFetch.mock.calls[0][0]).toContain(`${restBaseUrl}/patient?q=10001V`);
    expect(mockOpenmrsFetch.mock.calls[1][0]).toContain(`${restBaseUrl}/patient/server-patient-uuid?v=`);
  });

  it('returns null only for a valid empty search', async () => {
    mockOpenmrsFetch.mockResolvedValue({ data: { results: [] } } as FetchResponse);

    await expect(reconcilePatientCreation(identifiers, payload)).resolves.toBeNull();
  });

  it.each([{ data: null }, { data: {} }, { data: { results: null } }])(
    'fails closed on a malformed search response',
    async (response) => {
      mockOpenmrsFetch.mockResolvedValue(response as FetchResponse);

      await expect(reconcilePatientCreation(identifiers, payload)).rejects.toThrow(
        'patient reconciliation search returned an invalid response',
      );
    },
  );

  it('rejects a record with the same identifier but incompatible demographics', async () => {
    mockOpenmrsFetch.mockResolvedValue({
      data: { results: [{ ...serverPatient, person: { ...serverPatient.person, birthdate: '1991-02-03' } }] },
    } as never);

    await expect(reconcilePatientCreation(identifiers, payload)).rejects.toBeInstanceOf(PatientCreationConflictError);
  });

  it('rejects a match whose additional name, address, or nationality differs', async () => {
    const payloadWithIdentityDetails: Patient = {
      ...payload,
      person: {
        ...payload.person,
        names: [
          ...payload.person.names,
          {
            uuid: '',
            preferred: false,
            givenName: 'Ana',
            middleName: '',
            familyName: 'Perez',
            familyName2: '',
          },
        ],
        addresses: [{ preferred: true, address1: 'Jr. Lima 123', country: 'Perú' }],
        attributes: [{ attributeType: 'nationality-type-uuid', value: 'peru-concept-uuid' }],
      },
    };
    mockOpenmrsFetch.mockResolvedValue({ data: { results: [serverPatient] } } as never);

    await expect(reconcilePatientCreation(identifiers, payloadWithIdentityDetails)).rejects.toBeInstanceOf(
      PatientCreationConflictError,
    );
  });

  it('rejects multiple exact patients instead of choosing one', async () => {
    mockOpenmrsFetch.mockResolvedValue({
      data: { results: [serverPatient, { ...serverPatient, uuid: 'second-patient-uuid' }] },
    } as never);

    await expect(reconcilePatientCreation(identifiers, payload)).rejects.toBeInstanceOf(PatientCreationConflictError);
  });

  it('verifies the requested UUID and exact record identity', async () => {
    mockOpenmrsFetch.mockResolvedValue({ data: { ...serverPatient, uuid: 'different-uuid' } } as never);

    await expect(fetchAndVerifyCreatedPatient('server-patient-uuid', identifiers, payload)).rejects.toBeInstanceOf(
      PatientCreationConflictError,
    );
  });

  it('classifies only non-timeout 4xx responses as definitive rejections', () => {
    expect(isDefinitivePatientCreateRejection({ response: { status: 400 } })).toBe(true);
    expect(isDefinitivePatientCreateRejection({ response: { status: 408 } })).toBe(false);
    expect(isDefinitivePatientCreateRejection({ response: { status: 429 } })).toBe(false);
    expect(isDefinitivePatientCreateRejection({ response: { status: 499 } })).toBe(false);
    expect(isDefinitivePatientCreateRejection({ response: { status: 500 } })).toBe(false);
    expect(isDefinitivePatientCreateRejection(new Error('network error'))).toBe(false);
  });
});
