import {
  checkpointsHaveSameIdentifiers,
  checkpointsHaveSameScope,
  clearPatientCreationCheckpoint,
  fingerprintPatientPayload,
  loadPatientCreationCheckpoint,
  PATIENT_CREATION_CHECKPOINT_MAX_AGE_MS,
  PATIENT_CREATION_CHECKPOINT_STORAGE_KEY,
  PatientCreationCheckpointInvalidError,
  savePatientCreationCheckpoint,
  type PatientCreationCheckpoint,
} from './patient-creation-checkpoint';

const checkpoint: PatientCreationCheckpoint = {
  version: 2,
  state: 'create-pending',
  createdAt: Date.now(),
  payloadFingerprint: 'fingerprint',
  scope: {
    sessionId: 'session-id',
    userUuid: 'user-uuid',
    locationUuid: 'location-uuid',
    providerUuid: 'provider-uuid',
  },
  identifiers: [
    {
      fieldName: 'openmrsId',
      identifier: '10001V',
      identifierTypeUuid: 'identifier-type-uuid',
      locationUuid: 'location-uuid',
      preferred: true,
      autoGenerated: true,
      sourceUuid: 'source-uuid',
    },
  ],
};

describe('patient creation checkpoint', () => {
  beforeEach(() => {
    globalThis.sessionStorage.clear();
    vi.restoreAllMocks();
  });

  it('persists, validates, and clears a pending attempt', () => {
    expect(savePatientCreationCheckpoint(checkpoint)).toBe(true);
    expect(loadPatientCreationCheckpoint()).toEqual(checkpoint);
    expect(clearPatientCreationCheckpoint()).toBe(true);
    expect(loadPatientCreationCheckpoint()).toBeNull();
  });

  it('fails closed and preserves malformed stored data for investigation', () => {
    globalThis.sessionStorage.setItem(PATIENT_CREATION_CHECKPOINT_STORAGE_KEY, '{"version":2,"identifiers":[]}');

    expect(() => loadPatientCreationCheckpoint()).toThrow(PatientCreationCheckpointInvalidError);
    expect(globalThis.sessionStorage.length).toBe(1);
  });

  it('fails closed when session storage cannot persist the checkpoint', () => {
    const storageSpy = vi.spyOn(globalThis.sessionStorage, 'setItem').mockImplementation(() => {
      throw new Error('storage unavailable');
    });

    expect(savePatientCreationCheckpoint(checkpoint)).toBe(false);
    storageSpy.mockRestore();
  });

  it('compares identifier sets independently of their order', () => {
    const second = {
      fieldName: 'dni',
      identifier: '12345678',
      identifierTypeUuid: 'dni-type',
      locationUuid: 'location-uuid',
      preferred: false,
      autoGenerated: false,
    };
    expect(
      checkpointsHaveSameIdentifiers(
        [...checkpoint.identifiers, second],
        [second, ...checkpoint.identifiers],
      ),
    ).toBe(true);
    expect(checkpointsHaveSameIdentifiers(checkpoint.identifiers, [{ ...checkpoint.identifiers[0], identifier: 'X' }])).toBe(false);
  });

  it('binds a checkpoint to the exact authenticated session and clinical context', () => {
    expect(checkpointsHaveSameScope(checkpoint.scope, { ...checkpoint.scope })).toBe(true);
    expect(checkpointsHaveSameScope(checkpoint.scope, { ...checkpoint.scope, userUuid: 'other-user' })).toBe(false);
    expect(checkpointsHaveSameScope(checkpoint.scope, { ...checkpoint.scope, locationUuid: 'other-location' })).toBe(
      false,
    );
  });

  it('fails closed when a pending checkpoint is expired', () => {
    globalThis.sessionStorage.setItem(
      PATIENT_CREATION_CHECKPOINT_STORAGE_KEY,
      JSON.stringify({ ...checkpoint, createdAt: Date.now() - PATIENT_CREATION_CHECKPOINT_MAX_AGE_MS - 1 }),
    );

    expect(() => loadPatientCreationCheckpoint()).toThrow(PatientCreationCheckpointInvalidError);
  });

  it('creates a stable SHA-256 fingerprint without storing the patient payload', async () => {
    await expect(fingerprintPatientPayload('{"name":"Ana"}')).resolves.toMatch(/^[0-9a-f]{64}$/u);
    await expect(fingerprintPatientPayload('{"name":"Ana"}')).resolves.toBe(
      await fingerprintPatientPayload('{"name":"Ana"}'),
    );
  });
});
