import { logError } from '@openmrs/esm-framework';

export const PATIENT_CREATION_CHECKPOINT_STORAGE_KEY = 'openmrs:patient-registration:create:v2';
export const PATIENT_CREATION_CHECKPOINT_MAX_AGE_MS = 2 * 60 * 60 * 1000;
export const PATIENT_CREATION_CHECKPOINT_INVALID = 'PATIENT_CREATION_CHECKPOINT_INVALID';

export class PatientCreationCheckpointInvalidError extends Error {
  readonly code = PATIENT_CREATION_CHECKPOINT_INVALID;

  constructor() {
    super('The stored patient creation checkpoint is invalid or cannot be read.');
    this.name = 'PatientCreationCheckpointInvalidError';
  }
}

export interface PatientCreationIdentifierCheckpoint {
  fieldName: string;
  identifier: string;
  identifierTypeUuid: string;
  locationUuid: string;
  preferred: boolean;
  autoGenerated: boolean;
  sourceUuid?: string;
}

export interface PatientCreationCheckpoint {
  version: 2;
  state: 'create-pending' | 'patient-confirmed';
  createdAt: number;
  identifiers: Array<PatientCreationIdentifierCheckpoint>;
  payloadFingerprint: string;
  scope: PatientCreationCheckpointScope;
  patientUuid?: string;
}

export interface PatientCreationCheckpointScope {
  sessionId: string;
  userUuid: string;
  locationUuid: string;
  providerUuid: string;
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.trim().length > 0;
}

function isIdentifierCheckpoint(value: unknown): value is PatientCreationIdentifierCheckpoint {
  if (!value || typeof value !== 'object') {
    return false;
  }
  const identifier = value as Partial<PatientCreationIdentifierCheckpoint>;
  return (
    isNonEmptyString(identifier.fieldName) &&
    isNonEmptyString(identifier.identifier) &&
    isNonEmptyString(identifier.identifierTypeUuid) &&
    isNonEmptyString(identifier.locationUuid) &&
    typeof identifier.preferred === 'boolean' &&
    typeof identifier.autoGenerated === 'boolean' &&
    (!identifier.autoGenerated || isNonEmptyString(identifier.sourceUuid))
  );
}

function isCheckpoint(value: unknown): value is PatientCreationCheckpoint {
  if (!value || typeof value !== 'object') {
    return false;
  }
  const checkpoint = value as Partial<PatientCreationCheckpoint>;
  return (
    checkpoint.version === 2 &&
    (checkpoint.state === 'create-pending' || checkpoint.state === 'patient-confirmed') &&
    typeof checkpoint.createdAt === 'number' &&
    Number.isFinite(checkpoint.createdAt) &&
    checkpoint.createdAt <= Date.now() + 60_000 &&
    Date.now() - checkpoint.createdAt <= PATIENT_CREATION_CHECKPOINT_MAX_AGE_MS &&
    Array.isArray(checkpoint.identifiers) &&
    checkpoint.identifiers.length > 0 &&
    checkpoint.identifiers.every(isIdentifierCheckpoint) &&
    isNonEmptyString(checkpoint.payloadFingerprint) &&
    !!checkpoint.scope &&
    isNonEmptyString(checkpoint.scope.sessionId) &&
    isNonEmptyString(checkpoint.scope.userUuid) &&
    isNonEmptyString(checkpoint.scope.locationUuid) &&
    typeof checkpoint.scope.providerUuid === 'string' &&
    (checkpoint.state !== 'patient-confirmed' || isNonEmptyString(checkpoint.patientUuid))
  );
}

export async function fingerprintPatientPayload(payloadSignature: string): Promise<string | null> {
  try {
    const subtle = globalThis.crypto?.subtle;
    if (!subtle) {
      return null;
    }
    const digest = await subtle.digest('SHA-256', new TextEncoder().encode(payloadSignature));
    return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
  } catch (error) {
    logError(error, 'Fingerprint patient creation payload');
    return null;
  }
}

export function checkpointsHaveSameScope(left: PatientCreationCheckpointScope, right: PatientCreationCheckpointScope) {
  return (
    left.sessionId === right.sessionId &&
    left.userUuid === right.userUuid &&
    left.locationUuid === right.locationUuid &&
    left.providerUuid === right.providerUuid
  );
}

export function loadPatientCreationCheckpoint(): PatientCreationCheckpoint | null {
  try {
    const serialized = globalThis.sessionStorage?.getItem(PATIENT_CREATION_CHECKPOINT_STORAGE_KEY);
    if (!serialized) {
      return null;
    }
    const checkpoint: unknown = JSON.parse(serialized);
    if (!isCheckpoint(checkpoint)) {
      throw new PatientCreationCheckpointInvalidError();
    }
    return checkpoint;
  } catch (error) {
    logError(error, 'Load patient creation checkpoint');
    if (error instanceof PatientCreationCheckpointInvalidError) {
      throw error;
    }
    throw new PatientCreationCheckpointInvalidError();
  }
}

export function savePatientCreationCheckpoint(checkpoint: PatientCreationCheckpoint): boolean {
  if (!isCheckpoint(checkpoint)) {
    return false;
  }
  try {
    const storage = globalThis.sessionStorage;
    if (!storage) {
      return false;
    }
    storage.setItem(PATIENT_CREATION_CHECKPOINT_STORAGE_KEY, JSON.stringify(checkpoint));
    return storage.getItem(PATIENT_CREATION_CHECKPOINT_STORAGE_KEY) === JSON.stringify(checkpoint);
  } catch (error) {
    logError(error, 'Save patient creation checkpoint');
    return false;
  }
}

export function clearPatientCreationCheckpoint(): boolean {
  try {
    const storage = globalThis.sessionStorage;
    if (!storage) {
      return false;
    }
    storage.removeItem(PATIENT_CREATION_CHECKPOINT_STORAGE_KEY);
    return storage.getItem(PATIENT_CREATION_CHECKPOINT_STORAGE_KEY) === null;
  } catch (error) {
    logError(error, 'Clear patient creation checkpoint');
    return false;
  }
}

export function checkpointsHaveSameIdentifiers(
  left: Array<PatientCreationIdentifierCheckpoint>,
  right: Array<PatientCreationIdentifierCheckpoint>,
) {
  const signature = (identifier: PatientCreationIdentifierCheckpoint) =>
    [
      identifier.fieldName,
      identifier.identifier,
      identifier.identifierTypeUuid,
      identifier.locationUuid,
      identifier.preferred ? 'preferred' : 'not-preferred',
      identifier.autoGenerated ? 'generated' : 'manual',
      identifier.sourceUuid ?? '',
    ].join('\u001f');

  const leftSignatures = left.map(signature).sort();
  const rightSignatures = right.map(signature).sort();
  return leftSignatures.length === rightSignatures.length && leftSignatures.every((value, index) => value === rightSignatures[index]);
}
